# Generated by Django 3.2.9 on 2021-12-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('student_dob', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('school', models.TextField()),
                ('student_class', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
