# Generated by Django 3.2 on 2021-12-03 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0003_auto_20211203_0449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('class_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='studentapp.class')),
            ],
        ),
    ]
