# Generated by Django 3.2 on 2021-12-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0004_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='class_id',
        ),
        migrations.AddField(
            model_name='teacher',
            name='class_id',
            field=models.ManyToManyField(to='studentapp.Class'),
        ),
    ]
