# Generated by Django 3.2 on 2021-12-03 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0005_auto_20211203_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='studentapp.student')),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='studentapp.subject')),
            ],
        ),
    ]
